# Generated by Django 5.1.1 on 2024-10-31 02:34

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(validators=[usuarios.models.validar_edad_minima]),
        ),
    ]
