# Generated by Django 5.1.1 on 2024-10-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='email',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(default='usuario_inactivo', max_length=150, unique=True),
        ),
    ]
